# Generated by Django 3.1.5 on 2021-09-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c360app', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=800)),
                ('dob', models.DateField()),
                ('date_of_join', models.DateField()),
            ],
        ),
    ]
