# Generated by Django 3.1.5 on 2021-09-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c360app', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
