# Generated by Django 3.1.5 on 2021-09-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c360app', '0004_auto_20210915_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
